### ISSUE TITLE
Setup Github Actions to do a deploy for demo purposes

### ISSUE THREAD

**Issue by bmarshall511** [Highfivery/nextjs-starter#1]
Attempted to create a workflow to deploy the built site to `gh-pages` when changes are pushed to `main`, but ran into an issue with NPM not finding modules. See https://github.com/Highfivery/nextjs-starter/actions/runs/3482109524/jobs/5824042700

**Comment by Kd-Here** [comment]
Hey @bmarshall511 can I help you with automated test?

**Comment by bmarshall511** [comment]
@Kd-Here that would be great! Any help is very much appreciated.

**Comment by bmarshall511** [comment]
This isn't currently possible in Next.js 13 and Github pages. Next13 doesn't currently support `next export` and so can currently on be run on Node.js servers
