### ISSUE TITLE
documents(composer):  {"error":"Not Found"}

### ISSUE THREAD

**Issue by mrEckendonk** [Highfivery/nextjs-starter#14]
In the documentation, https://github.com/Highfivery/nextjs-starter/wiki/WordPress-Setup composer.json is missing if using the link: then download our [composer.json](https://github.com/Highfivery/nextjs-starter/main/backend/wordpress/composer.json).

It should be:
https://raw.githubusercontent.com/Highfivery/nextjs-starter/main/backend/wordpress/composer.json

instead of

https://github.com/Highfivery/nextjs-starter/main/backend/wordpress/composer.json

```
{"error":"Not Found"}
````

**Comment by bmarshall511** [comment]
Thanks for pointing that out @mrEckendonk , it's been updated accordingly.
