### ISSUE TITLE
Root composer.json requires highfivery/wordpress-gutenberg-ant-design ^0.1.0, found highfivery/wordpress-gutenberg-ant-design[dev-main] but it does not match the constraint.

### ISSUE THREAD

**Issue by mrEckendonk** [Highfivery/nextjs-starter#15]
Problem 1
    - Root composer.json requires highfivery/wordpress-gutenberg-ant-design ^0.1.0, found highfivery/wordpress-gutenberg-ant-design[dev-main] but it does not match the constraint.

Solution:
   - Download https://github.com/Highfivery/wordpress-gutenberg-ant-design/archive/refs/heads/main.zip and install manually, then run `composer install`.

**Comment by bmarshall511** [comment]
You're absolutely right. Check out the comment I posted on your other issue: https://github.com/Highfivery/nextjs-starter/issues/16#issuecomment-1410371705

I need to get the docs updated, just moving at lightspeed getting ready for the first beta release
