### ISSUE TITLE
.env.sample is empty

### ISSUE THREAD

**Issue by mrEckendonk** [Highfivery/nextjs-starter#16]
The .env.sample is empty, guess the values are the same as in the WebDevStudios repo

https://github.com/Highfivery/nextjs-starter/blob/4953a64a4835ed071cff22dd025ed3d5003b9752/.env.sample

```
# Your WordPress username.
WORDPRESS_APPLICATION_USERNAME="YOUR_WORDPRESS_USERNAME"

# Your WordPress application password. Requires WordPress 5.6 and above.
# See https://make.wordpress.org/core/2020/11/05/application-passwords-integration-guide/
WORDPRESS_APPLICATION_PASSWORD="YOUR_GENERATED_APPLICATION_PASSWORD"
```

**Comment by mrEckendonk** [comment]
😄 I was a little to fast, the last line in the backend setup confused me

Copy and paste the password into a safe location. You will need to add both your WordPress username and Application password to the .env file for the front end.

**Comment by bmarshall511** [comment]
Hey @mrEckendonk, you're right on the money actually. Our team has been going 24/7 lately getting ready for the first beta release, so those docs aren't exactly up-to-date 🫣

We've actually simplified the process quite a bit. The only environment variable you need is: 

`NEXT_PUBLIC_WORDPRESS_API_URL=http://headless-wordpress.local`

And then just the plugins listed in the .env file. You'll also need this plugin https://github.com/Entermedia-LLC/wordpress-gutenberg-ant-design

I'll try to make a point of getting the docs updated, but let me know if you run into any problems.
